---
- name: Start creation tasks
  when: not aws_vpc_teardown | bool
  block:
    - name: Start creation tasks
      ansible.builtin.include_tasks:
        file: create.yml

    - name: Get role output
      ansible.builtin.include_tasks:
        file: role_output.yml
      when: aws_vpc_set_role_output | bool

- name: Start teardown tasks
  ansible.builtin.include_tasks:
    file: teardown.yml
  when: aws_vpc_teardown | bool


...
# vim:ft=yaml.ansible
