---
- name: Delete an AWS VPC and its network components
  hosts: localhost

  tasks:
    - name: Delete VPC named "{{ aws_vpc_name }}"
      ansible.builtin.include_role:
        name: jce_redhat.cloud_infra.aws_vpc
      vars:
        aws_vpc_name: ansible-test-vpc
        aws_vpc_teardown: true

...
